# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - "6"
before_script:
  - chmod u+rx ./travis.sh
  - ./travis.sh
  - npm install -g gulp
  - npm test
script:
  - gulp build
after_success:
  - gulp deploy
env:
  global:
  - ENCRYPTION_LABEL: "b49a64915829"
  - GIT_COMMITTER_EMAIL: "plauper@yahoo.com"
  - GIT_COMMITTER_NAME: "Patrick Lauper"
