# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
  - gulp test
script:
  - gulp build
after_success:
  - gulp deploy
